version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_reservationspy
    environment:
      MYSQL_ROOT_PASSWORD: Pass2025
      MYSQL_DATABASE: reservationspy
      MYSQL_USER: root
      MYSQL_PASSWORD: Pass2025
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  backend:
    build: ./reservationspy-api
    container_name: reservationspy_api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Pass2025
      DB_NAME: reservationspy
    volumes:
      - ./reservationspy-api:/usr/src/app
    working_dir: /usr/src/app
    command: ["node", "src/index.js"]

  frontend:
    build: ./reservationspy-ui
    container_name: reservationspy_ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./reservationspy-ui:/usr/src/app
    stdin_open: true
    tty: true

volumes:
  mysql-data:
